spring:
  application:
    name: java-api-search-module
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 7529
  servlet:
    context-path: /api

dubbo:
  application:
    name: dubbo-springboot-demo-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://192.168.10.148:2181