spring:
  application:
    name: java-api-search-module
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_java_api_doc
    username: root
    password: 1111

  redis:
    port: 6379
    host: localhost
    database: 4
    lettuce:
      pool:
        max-wait: 100ms
        max-idle: 8
        min-idle: 0
        max-active: 8
server:
  port: 7529
  servlet:
    context-path: /api
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
#      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

dubbo:
  consumer:
    timeout: 300000
  provider:
    timeout: 300000
  application:
    name: dubbo-java-api-doc-search-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://192.168.10.148:2181